#!/bin/bash

export PATH="/opt/ifi/anaconda3/bin:$PATH"
source ~/.bashrc
conda activate env39

echo "Job done at $HOSTNAME"
echo "Seeded timescale"

python3 main3.py -c conf/Z_TWoff_B_seeded.yaml -o RobinHPC_seedtest_timescale -w 300

#!/usr/bin/bash

#SBATCH --job-name=Zero_TanhWoff
#SBATCH --output=log_ZeroTanhWoff.txt
#SBATCH --array=1-10      # Creates 4 jobs, with `${SLURM_ARRAY_TASK_ID}` values from 1 to 4
#SBATCH --ntasks=10
#SBATCH --mem 2G

# load anaconda and your environment
source ~/.bashrc
conda activate env39

# Run your program with "srun your_command"
srun bash -c "echo hello ${SLURM_ARRAY_TASK_ID}" &

squeue
scontrol show node
sacct -j 12972 --format=JobID,Jobname%30,Start,End,Elapsed,REQCPUS,ALLOCTRES%30

# Til ifi maskinen
# KJøres på HPC  
rsync --progress -a result/* henrme@login.ifi.uio.no:~/resultater_timescale/
rsync --progress result/* henrme@login.ifi.uio.no:~/resultater/
rsync --progress -a result/G_SUfq_B_exLimit/* henrme@login.ifi.uio.no:~/resultater/G_SUfq_B_exLimit/

# Disse må kjøres
rsync --progress -a miljo_timescale/* henrme@login.ifi.uio.no:~/resultater_timescale/miljo_timescale
rsync --progress -a kontrollers_timescale/* henrme@login.ifi.uio.no:~/timescale/kontrollers_timescale
rsync --progress -a miljo/* henrme@login.ifi.uio.no:~/timescale/miljo_timescale2
rsync --progress -a opprydding/* henrme@login.ifi.uio.no:~/timescale/opprydding


# Fra ifi til min data:
# Kjøres på min
rsync -chavzP --stats henrme@login.ifi.uio.no:~/resultater /mnt/c/Users/henri/Documents/GitHub/
rsync -chavzP --stats henrme@login.ifi.uio.no:~/timescale /mnt/c/Users/henri/Documents/GitHub/timescale/
rsync -chavzP --stats henrme@login.ifi.uio.no:~/resultater_timescale /mnt/c/Users/henri/Documents/GitHub/resultater_timescale/
